/**
 * Storage URL helpers.
 *
 * Pure string builders — no Supabase client and no secrets, so this module is
 * safe to import from Server Components, client components and the data
 * modules in `src/lib/data` alike. `@/lib/supabase` holds the service-role
 * client and must stay server-side; it re-exports everything here.
 */

const SUPABASE_PROJECT_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL ??
  "https://ipmdyrxfptdsulfhxjkb.supabase.co";

export const AVATARS_BUCKET = "avatars";

/**
 * Public bucket holding the club's documents — syllabus PDFs today.
 *
 * Object keys are the human filenames the club uploads with (see
 * `publishedSyllabi` in `src/lib/data/syllabus.ts`), so this bucket is not
 * content-addressed the way `avatars` is: replacing a syllabus means replacing
 * the object under the same key.
 */
export const PDFS_BUCKET = "pdfs";

/** Public, CDN-served URL for an arbitrary object in a bucket. */
export function storagePublicUrl(bucket: string, path: string): string {
  return `${SUPABASE_PROJECT_URL}/storage/v1/object/public/${bucket}/${path}`;
}

/**
 * Public URL for a document in the `pdfs` bucket.
 *
 * Each path segment is percent-encoded because the club's object keys are the
 * filenames they uploaded (`MATH OLYMPIAD SYLLABUS.pdf`), and a raw space in a
 * URL is invalid even though browsers paper over it. Encoding segment-by-segment
 * rather than with `encodeURIComponent(path)` keeps the slashes in a nested key
 * intact.
 *
 * `download` makes Supabase answer with `Content-Disposition: attachment`, so a
 * "Download" link saves the file instead of opening the browser's PDF viewer.
 */
export function pdfUrl(
  path: string,
  options: { download?: boolean } = {},
): string {
  const encoded = path.split("/").map(encodeURIComponent).join("/");
  const url = storagePublicUrl(PDFS_BUCKET, encoded);
  return options.download ? `${url}?download` : url;
}

/**
 * URL for a pre-optimised WebP asset under `optimized/` in the avatars bucket.
 *
 * These are generated by `scripts/optimize-bucket-images.mjs` at exactly the
 * size they are displayed (2x for retina), so they are served verbatim and
 * never touch the Next.js image optimizer — no Vercel image transformations,
 * and the objects carry an immutable one-year `cache-control`.
 */
export function bucketImage(path: string): string {
  return storagePublicUrl(AVATARS_BUCKET, `optimized/${path}`);
}

/**
 * `true` when a public-object URL already points at a WebP under `optimized/`,
 * i.e. the final display bytes produced by `scripts/optimize-bucket-images.mjs`.
 * Those objects carry an immutable one-year cache and are already the size the
 * browser wants — transforming them again is pure wasted egress.
 */
export function isOptimizedObjectUrl(url: string): boolean {
  return /\/storage\/v1\/object\/public\/avatars\/optimized\//.test(url);
}

/**
 * Turn a Supabase *public object* URL into a *render* URL, so Supabase's own
 * CDN performs the resize/encode instead of Vercel's image optimizer.
 *
 * **Egress guard.** An object that is already pre-optimised (`optimized/*`,
 * produced by the bucket script) is returned **untouched** — the `render/image`
 * endpoint would otherwise pull the original back out of storage and re-encode on
 * every request, which is the single largest driver of metered egress in this
 * project. Only genuinely multi-megabyte *originals* that are not yet optimised
 * should be forced through the transform.
 *
 * Returns the input untouched when it isn't a public object URL.
 */
export function renderedImageUrl(
  url: string,
  options: { width: number; height?: number; quality?: number },
): string {
  if (isOptimizedObjectUrl(url)) return url;

  const match =
    /^(https?:\/\/[^/]+)\/storage\/v1\/object\/public\/(.+)$/.exec(url);
  if (!match) return url;

  const params = new URLSearchParams({
    width: String(options.width),
    resize: "cover",
    quality: String(options.quality ?? 80),
    format: "webp",
  });
  if (options.height) params.set("height", String(options.height));

  return `${match[1]}/storage/v1/render/image/public/${match[2]}?${params.toString()}`;
}

/**
 * Resolve a stored avatar/profile image to the URL that should actually be sent to
 * the browser, choosing the cheapest option that still looks right.
 *
 * - A URL that is **already optimised** (`optimized/*`, or a small immutable
 *   upload such as the 512px WebP `profile-form`/`/api/upload` produce) is
 *   served **directly** — no `render/image` transform, so Supabase never re-pulls
 *   the original for it.
 * - A raw legacy original is forced through `render/image` once per distinct width
 *   so the browser gets a small 2x WebP instead of a multi-megabyte file.
 *
 * Prefer this over calling `renderedImageUrl` by hand on stored avatar URLs: it
 * centralises the "is this already small?" decision that used to be split across
 * the profile form and the blog author card, and it is what keeps new uploads off
 * the metered transform path at all.
 */
export function avatarUrl(
  url: string | null | undefined,
  width: number,
): string | null {
  if (!url) return null;
  // Blob previews are client-in-memory and can never be touched by a CDN.
  if (url.startsWith("blob:")) return url;
  // Already-final bytes → serve verbatim.
  if (isOptimizedObjectUrl(url)) return url;
  // A UUID-named upload in the avatars root is what `/api/upload` writes — the
  // profile form compresses it to ≤512px WebP before the request, so it is
  // already small and immutable. Serving it directly bypasses the transform.
  if (/\/avatars\/[0-9a-f-]{36}\.(webp|png|jpe?g)$/.test(url)) return url;
  // Everything else is treated as a raw legacy original → resize once via CDN.
  return renderedImageUrl(url, { width });
}

