/**
 * Storage URL helpers.
 *
 * Pure string builders — no Supabase client and no secrets, so this module is
 * safe to import from Server Components, client components and the data
 * modules in `src/lib/data` alike. `@/lib/supabase` holds the service-role
 * client and must stay server-side; it re-exports everything here.
 */

const SUPABASE_PROJECT_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL ??
  "https://ipmdyrxfptdsulfhxjkb.supabase.co";

export const AVATARS_BUCKET = "avatars";

/**
 * Public bucket holding the club's documents — syllabus PDFs today.
 *
 * Object keys are the human filenames the club uploads with (see
 * `publishedSyllabi` in `src/lib/data/syllabus.ts`), so this bucket is not
 * content-addressed the way `avatars` is: replacing a syllabus means replacing
 * the object under the same key.
 */
export const PDFS_BUCKET = "pdfs";

/** Public, CDN-served URL for an arbitrary object in a bucket. */
export function storagePublicUrl(bucket: string, path: string): string {
  return `${SUPABASE_PROJECT_URL}/storage/v1/object/public/${bucket}/${path}`;
}

/**
 * Public URL for a document in the `pdfs` bucket.
 *
 * Each path segment is percent-encoded because the club's object keys are the
 * filenames they uploaded (`MATH OLYMPIAD SYLLABUS.pdf`), and a raw space in a
 * URL is invalid even though browsers paper over it. Encoding segment-by-segment
 * rather than with `encodeURIComponent(path)` keeps the slashes in a nested key
 * intact.
 *
 * `download` makes Supabase answer with `Content-Disposition: attachment`, so a
 * "Download" link saves the file instead of opening the browser's PDF viewer.
 */
export function pdfUrl(
  path: string,
  options: { download?: boolean } = {},
): string {
  const encoded = path.split("/").map(encodeURIComponent).join("/");
  const url = storagePublicUrl(PDFS_BUCKET, encoded);
  return options.download ? `${url}?download` : url;
}

/**
 * URL for a pre-optimised WebP asset under `optimized/` in the avatars bucket.
 *
 * These are generated by `scripts/optimize-bucket-images.mjs` at exactly the
 * size they are displayed (2x for retina), so they are served verbatim and
 * never touch the Next.js image optimizer — no Vercel image transformations,
 * and the objects carry an immutable one-year `cache-control`.
 */
export function bucketImage(path: string): string {
  return storagePublicUrl(AVATARS_BUCKET, `optimized/${path}`);
}

/**
 * Turn a Supabase *public object* URL into a *render* URL, so Supabase's own
 * CDN performs the resize/encode instead of Vercel's image optimizer.
 *
 * Use this for image URLs that aren't known at build time — e.g. an author
 * avatar pasted into the CMS pointing at a raw multi-megabyte original.
 * Returns the input untouched when it isn't a public object URL.
 */
export function renderedImageUrl(
  url: string,
  options: { width: number; height?: number; quality?: number },
): string {
  const match =
    /^(https?:\/\/[^/]+)\/storage\/v1\/object\/public\/(.+)$/.exec(url);
  if (!match) return url;

  const params = new URLSearchParams({
    width: String(options.width),
    resize: "cover",
    quality: String(options.quality ?? 80),
    format: "webp",
  });
  if (options.height) params.set("height", String(options.height));

  return `${match[1]}/storage/v1/render/image/public/${match[2]}?${params.toString()}`;
}

