/**
 * Storage URL helpers.
 *
 * Pure string builders — no Supabase client and no secrets, so this module is
 * safe to import from Server Components, client components and the data
 * modules in `src/lib/data` alike. `@/lib/supabase` holds the service-role
 * client and must stay server-side; it re-exports everything here.
 */

const SUPABASE_PROJECT_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL ??
  "https://ipmdyrxfptdsulfhxjkb.supabase.co";

export const AVATARS_BUCKET = "avatars";

/** Public, CDN-served URL for an arbitrary object in a bucket. */
export function storagePublicUrl(bucket: string, path: string): string {
  return `${SUPABASE_PROJECT_URL}/storage/v1/object/public/${bucket}/${path}`;
}

/**
 * URL for a pre-optimised WebP asset under `optimized/` in the avatars bucket.
 *
 * These are generated by `scripts/optimize-bucket-images.mjs` at exactly the
 * size they are displayed (2x for retina), so they are served verbatim and
 * never touch the Next.js image optimizer — no Vercel image transformations,
 * and the objects carry an immutable one-year `cache-control`.
 */
export function bucketImage(path: string): string {
  return storagePublicUrl(AVATARS_BUCKET, `optimized/${path}`);
}

/**
 * Turn a Supabase *public object* URL into a *render* URL, so Supabase's own
 * CDN performs the resize/encode instead of Vercel's image optimizer.
 *
 * Use this for image URLs that aren't known at build time — e.g. an author
 * avatar pasted into the CMS pointing at a raw multi-megabyte original.
 * Returns the input untouched when it isn't a public object URL.
 */
export function renderedImageUrl(
  url: string,
  options: { width: number; height?: number; quality?: number },
): string {
  const match =
    /^(https?:\/\/[^/]+)\/storage\/v1\/object\/public\/(.+)$/.exec(url);
  if (!match) return url;

  const params = new URLSearchParams({
    width: String(options.width),
    resize: "cover",
    quality: String(options.quality ?? 80),
    format: "webp",
  });
  if (options.height) params.set("height", String(options.height));

  return `${match[1]}/storage/v1/render/image/public/${match[2]}?${params.toString()}`;
}

